-- Remove existing tables (if recreating from scratch)
DROP TABLE IF EXISTS
  public.free_space_user_added_tasks,
  public.games,
  public.photos,
  public.tasks,
  public.users,
  public.users_tasks
CASCADE;

-- Create tables with modern identity columns
CREATE TABLE public.free_space_user_added_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    user_task_id BIGINT NOT NULL
);

CREATE TABLE public.games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name TEXT NOT NULL,
    tagline TEXT NOT NULL,
    photo_upload_path TEXT,
    created_by_user_id BIGINT NOT NULL,
    secret TEXT NOT NULL,
    expires TIMESTAMP,
    number_of_custom_tasks NUMERIC NOT NULL,
    game_status TEXT NOT NULL
);

CREATE TABLE public.photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    file_path TEXT NOT NULL,
    user_task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    game_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    type TEXT NOT NULL
);

CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    profile_photo TEXT
);

CREATE TABLE public.users_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    completed BOOLEAN NOT NULL,
    grid_row NUMERIC NOT NULL,
    grid_column NUMERIC NOT NULL,
    completed_at TIMESTAMPTZ
);

-- Add foreign key constraints (recommended)
ALTER TABLE public.free_space_user_added_tasks
  ADD CONSTRAINT fk_user_task
  FOREIGN KEY (user_task_id) 
  REFERENCES public.users_tasks(id);

ALTER TABLE public.photos
  ADD CONSTRAINT fk_user_task
  FOREIGN KEY (user_task_id) 
  REFERENCES public.users_tasks(id);

ALTER TABLE public.tasks
  ADD CONSTRAINT fk_game
  FOREIGN KEY (game_id) 
  REFERENCES public.games(id);

ALTER TABLE public.users_tasks
  ADD CONSTRAINT fk_user
  FOREIGN KEY (user_id) 
  REFERENCES public.users(id),
ADD CONSTRAINT fk_task
  FOREIGN KEY (task_id) 
  REFERENCES public.tasks(id);

-- Enable Row Level Security (optional - Supabase default is disabled)
ALTER TABLE public.free_space_user_added_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users_tasks ENABLE ROW LEVEL SECURITY;

-- Create indexes for common lookups
CREATE INDEX idx_free_space_tasks_user ON public.free_space_user_added_tasks(user_id);
CREATE INDEX idx_games_creator ON public.games(created_by_user_id);
CREATE INDEX idx_photos_user ON public.photos(user_id);
CREATE INDEX idx_tasks_game ON public.tasks(game_id);
CREATE INDEX idx_users_email ON public.users(email);
CREATE INDEX idx_users_tasks_completion ON public.users_tasks(completed);